[project]
# authors = [""]
channels = ["conda-forge"]
description = "Add a short description here"
name = "VU-ML-project"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.2.*"
numpy = ">=2.2.2,<3"
matplotlib = ">=3.10.0,<4"
pandas = ">=2.2.3,<3"
ipykernel = ">=6.29.5,<7"
pytorch = ">=2.5.1,<3"
